params:
  seed: 23123

  # environment wrapper clipping
  env:
    # added to the wrapper
    clip_observations: 5.0
    # can make custom wrapper?
    clip_actions: 1.0

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  # doesn't have this fine grained control but made it close
  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer

          val: 0.22
        fixed_sigma: True
    mlp:
      units: [1024, 1024, 512, 512]
      activation: elu
      d2rl: True

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    name: shadow_hand_train
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False

    ppo: True
    mixed_precision: False

    # Input/value normalization and GAE
    normalize_input: True
    normalize_value: False
    value_bootstrap: True

    num_actors: -1  # configured from the script (based on num_envs)

    reward_shaper:
      scale_value: 0.1

    normalize_advantage: True

    # gamma, lambda(tau)
    gamma: 0.99
    tau : 0.95

    # learning rate / schedule
    learning_rate: 3e-4
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.016


    # PPO
    e_clip: 0.2
    entropy_coef: 0.005
    clip_value: True

    # Rollout, batch, and epoch settings
    horizon_length: 8
    minibatch_size: 1024
    mini_epochs: 5

    # gradient
    grad_norm: 1.0
    truncate_grads: True

    # Miscellaneous
    critic_coef: 4
    seq_length: 4
    bounds_loss_coef: 0.0
    score_to_win: 20000
    max_epochs: 5000
    save_best_after: 50
    save_frequency: 100

    player:
      deterministic: True
      games_num: 1000
      print_stats: True